### ISSUE TITLE
Complexity

### ISSUE THREAD

**Issue by b3bry** [donniepropst/FreeCol-cosc442-finalproject#4]
ColonizationMapLoader.java - 7.00
TerrainGenerator.java - 8.76
ServerColony.java - 7.12
ServerUnit.java - 12.06
ServerPlayer.java - 6.47
InGameController.java - 6.15
ConnectController.java - 4.94

**Comment by donniepropst** [comment]
I used Randoop to generate test cases for ServerColony, ServerUnit, ServerPlayer (from this list)
and the Tile class which was one of the more used classes.  
Currently in branch donnie-tests, will merge tonight

**Comment by b3bry** [comment]
Test cases generated closing issue
